name: Build and push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:   
    - name: Log into Docker
      uses: docker/login-action@v1
      with:
        username: catsduck
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: catsduck/electrumx:latest
